### ISSUE TITLE
Move constructor does not actually work

### ISSUE THREAD

**Issue by VincentWo** [reo7sp/tgbot-cpp#131]
This code:

```
#include <tgbot/tgbot.h>
#include <optional>
auto api_token = "API_TOKEN";
auto create_bot()
{
    return std::optional{TgBot::Bot{api_token}};
}
auto main() -> int
{
    auto bot = std::move(*create_bot()));
    auto longPoll = TgBot::TgLongPoll{bot};
    while(true)
    {
         longPoll.start();
    }
    return 0;
}
```
Compiles, but actually segfaults as soon as a message is received. This is because `TgBot::Bot` construct its member `_eventHandler` with a reference to `_eventBroadcaster`, which get invalidated by the Move Constructor. 

There seem to be 3 different solutions to this:

1. Just delete the move (and copy?) constructors. The easiest solution, but maybe not the nicest from a usage point of view.
2. Just make the `_eventBroadcast` a smart-pointer. Actually tried this out and it works, probably not so nice from a performant point of view, but probably does not matter.
3. Make it possible to change the reference hold by `_eventBroadcaster`. Probably the cleanest solution in term of performance, but creates a bit of a weird interface for `EventBroadcaster` and I have no idea how complicated this is.

Without having any real knowledge of the codebase Option 2 looks the best to me, implementing it seems to be a two lines code change.

**Comment by ZaMaZaN4iK** [comment]
I confirm: we have a problem here. Let's discuss your solutions:

1. Yes, removing move and copy constructors resolves the problem. However, instead of just marking them as `delete` - we can provide to the user our own proper implementation. I don't want to delete copy and move ctors.
2. Smart-pointer is a good choice here. I think we don't care a lot here about smart-pointer (`std:shared_ptr`) overhead.
3. Don't understand the solution here.

However I can suggest a solution from my side: in `TgBot::Bot` move `_eventHandler` and `_eventBroadcaster` into one entity. And during copying and moving it will work in proper way. What do you think? @VincentWo
