### ISSUE TITLE
Bad request, Gateway timout errors

### ISSUE THREAD

**Issue by teor292** [reo7sp/tgbot-cpp#162]
Hi, using this library I sometimes encountered "bad request" error or "gateway timeout" error. After some investigations I figure out  that this error can be related to http send boundary, namely - symbol ';'
After I delete this symbol and some others symbols from generateRandomString function -> I send more than 200 messages and error didn't occurred. 
My current symbols line for generation of boundary looks like this:

"qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890-=[]\\./!@#$%^&*()_+{}|:\"<>?~"

You can test this bug. Just append to generated boundary symbol ';' and try send photo. So, I propose remove at least symbol ';' from symbols line in generateRandomString  function.

**Comment by MPSMPS** [comment]
Hi, thanks @teor292  for this hint. This problem is bothering me since months. Exactly same behavior as you described.
Based on your hint I changed generateRandomString to return always the same characters (only the non alpha numeric ones). It works reliable but when I add the ';' I get timeouts. I confirmed it several times.
