### ISSUE TITLE
move parse and parseJson methods of TgTypeParser.cpp to individual types

### ISSUE THREAD

**Issue by naveenvhegde** [reo7sp/tgbot-cpp#64]
TgTypeParser.cpp has grown to big. We can refactor its method into each types.

**Comment by naveenvhegde** [comment]
@reo7sp I have refactored few smaller types Audio, MaskPosition, Sticker, User and PhotoSize in [commit](https://github.com/naveenvhegde/tgbot-cpp/tree/f974bb7460b0031b9a21248251f8033984a022d0). Please take look. If it looks good. I'll proceed with all other types.  Thanks

**Comment by reo7sp** [comment]
@naveenvhegde Sorry for the delay. I have reviewed your commit now.

<br>

Review: 

# ***Great! Thanks!*** 

Just 2 comments:
1. The lib uses camelCase naming. So you should rename `from_json` to `fromJson` and `to_json` to `toJson`.
2. Ugh, I should have created function `removeLastComma(result);` instead of writing everywhere `result.erase(result.length() - 1);` a long time ago. You can make this little one-line function.
